[package]
name = "game_2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy-table = "6.1.4"
getch-rs = "0.1.3"
once_cell = "1.17.1"
owo-colors = "3.5.0"
rand = "0.8.5"
